### ISSUE TITLE
Handle old Lambda memory limit in some regions

### ISSUE THREAD

**Issue by dnaphas-vri** [VerticalRelevance/control-broker#27]
Control Broker failed to deploy in us-west-2 with the error:

> Failed resources:
[700](https://github.com/douglasnaphas/vr-sl-c/runs/6870605599?check_suite_focus=true#step:8:701)
ControlBrokerV0x10x1 | 10:24:35 PM | CREATE_FAILED        | AWS::Lambda::Function               | EvalEngineLambdalith (EvalEngineLambdalith7C0C8D75) Resource handler returned message: "'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008 (Service: Lambda, Status Code: 400, Request ID: 47c3470e-fcdd-4587-a262-141d57347850)" (RequestToken: 4bfae6c8-ccba-2806-90e4-e823f0238471, HandlerErrorCode: InvalidRequest)p

It looks like it was this issue:

https://stackoverflow.com/a/71060624/2260686

**Comment by dnaphas-vri** [comment]
@cschneider-vertical-relevance Is [this memory limit](https://github.com/VerticalRelevance/control-broker/blob/e1b3b4525482c99320f8fb4936098af04669a1d7/stacks/control_broker_stack.py#L1024) 10240 because lower amounts were found to be not enough? Could we do 3008? As this Issue’s description states, some regions seem to have problems with memory limits above 3008.

**Comment by dnaphas-vri** [comment]
Ok, I’ll submit a PR shortly changing it to 3008.

**Comment by dnaphas-vri** [comment]
@cschneider-vertical-relevance Could you https://github.com/VerticalRelevance/control-broker/pull/29, which makes the change discussed above?

**Comment by cschneider-vertical-relevance** [comment]
tracking power tune here #30
